
-- TTT WEAPON STATS
-- used to base new weapon stats on vanilla guns
-- shared between my addons that add weapons

-- AMMO TYPES
TTT_AMMOTYPE_PISTOL			= "Pistol"
TTT_AMMOTYPE_SMG			= "smg1"
TTT_AMMOTYPE_DEAGLE			= "AlyxGun"
TTT_AMMOTYPE_RIFLE			= "357"
TTT_AMMOTYPE_SHOTGUN		= "Buckshot"
TTT_AMMOTYPE_HUGE			= "AirboatGun"

-- AMMO ENTS
TTT_AMMOENT_PISTOL			= "item_ammo_pistol_ttt"
TTT_AMMOENT_SMG				= "item_ammo_smg1_ttt"
TTT_AMMOENT_DEAGLE			= "item_ammo_revolver_ttt"
TTT_AMMOENT_RIFLE			= "item_ammo_357_ttt"
TTT_AMMOENT_SHOTGUN			= "item_box_buckshot_ttt"

-- SHOTGUN
TTT_SHOTGUN_DAMAGE			= 11
TTT_SHOTGUN_CONE			= 0.082
TTT_SHOTGUN_DELAY			= 0.8
TTT_SHOTGUN_CLIPSIZE		= 8
TTT_SHOTGUN_CLIPMAX			= 24
TTT_SHOTGUN_NUMSHOTS		= 8
TTT_SHOTGUN_RECOIL			= 7

-- RIFLE
TTT_RIFLE_DELAY				= 1.5
TTT_RIFLE_RECOIL			= 7
TTT_RIFLE_DAMAGE			= 50
TTT_RIFLE_CONE				= 0.005
TTT_RIFLE_CLIPSIZE			= 10
TTT_RIFLE_CLIPMAX			= 20

-- DEAGLE
TTT_DEAGLE_RECOIL			= 6
TTT_DEAGLE_DAMAGE			= 37
TTT_DEAGLE_DELAY			= 0.6
TTT_DEAGLE_CONE				= 0.02
TTT_DEAGLE_CLIPSIZE			= 8
TTT_DEAGLE_CLIPMAX			= 36

-- PISTOL
TTT_PISTOL_RECOIL			= 1.5
TTT_PISTOL_DAMAGE			= 25
TTT_PISTOL_DELAY			= 0.38
TTT_PISTOL_CONE				= 0.02
TTT_PISTOL_CLIPSIZE			= 20
TTT_PISTOL_CLIPMAX			= 60

-- MAC 10
TTT_MAC10_DAMAGE			= 12
TTT_MAC10_DELAY				= 0.065
TTT_MAC10_CONE				= 0.03
TTT_MAC10_CLIPSIZE			= 30
TTT_MAC10_CLIPMAX			= 60
TTT_MAC10_RECOIL			= 1.15

-- M16
TTT_M16_DELAY				= 0.19
TTT_M16_RECOIL				= 1.6
TTT_M16_DAMAGE				= 23
TTT_M16_CONE				= 0.018
TTT_M16_CLIPSIZE			= 20
TTT_M16_CLIPMAX				= 60

-- GLOCK
TTT_GLOCK_RECOIL			= 0.9
TTT_GLOCK_DAMAGE			= 12
TTT_GLOCK_DELAY				= 0.10
TTT_GLOCK_CONE				= 0.028
TTT_GLOCK_CLIPSIZE			= 20
TTT_GLOCK_CLIPMAX			= 60

-- HUGE
TTT_HUGE_DAMAGE				= 7
TTT_HUGE_DELAY				= 0.06
TTT_HUGE_CONE				= 0.09
TTT_HUGE_CLIPSIZE			= 150
TTT_HUGE_CLIPMAX			= 150
TTT_HUGE_RECOIL				= 1.9
